config/routes.rb
Rails.application.routes.draw do

  get 'shoppingcarts/show'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'comments' => 'pages#index'
  
  root 'static_pages#home'

  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users do
    resource :shoppingcart
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :items
  resources :comments

end

app/models/item.rb
class Item < ActiveRecord::Base	
	include PgSearch
	belongs_to :shoppingcart
	has_many :users, through: :shoppingcart
	default_scope -> {order(created_at: :asc)}
	validates :name, presence: true, length: { maximum: 100 }
	validates :description, presence: true, 
		length: { maximum: 1000 }
	VALID_PRICE_REGEX = /\A\d+(?:\.\d{0,3})?\z/
	validates :price, presence: true, 
		:format => { with: VALID_PRICE_REGEX }, 
		:numericality => {:greater_than => 0}
	validates_uniqueness_of :name

	scope :sorted, ->{ order(name: :asc) }
	pg_search_scope :search,
                  against: [
                    :name,
                    :description,
                    :price
                  ],
                  using: {
                    tsearch: {
                      prefix: true,
                      normalization: 2
                    }
                  }


	def Item.priceMaker
		num = Faker::Commerce.price
		num = '%.2f' % num 
		return num		
	end

	def priceFormat
		"$#{sprintf("%.2f" , price)}"
	end 

	def Item.nameMaker
		name = ""
		loop do
			name = Faker::Commerce.product_name
#			puts "Name: #{name}"
			item = Item.find_by(name: name)
			if item.nil? 
#				puts "#{name} not found"
				break 
			end
		end	
#		puts "Returning Name #{name}"
		return name
	end

	def Item.newName
		Faker::Commerce.product_name
	end


	def Item.gen
		100.times {
			@itemN = Item.new 
			@itemN.description = "Some Item"
			@itemN.price = 100
			@itemN.name = Item.nameMaker
			puts "Saving #{@itemN.name}"
			@itemN.save!
		}
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_filter :search_items
	before_action :logged_in_user, only: [:edit, :update, :destroy]
	before_action :admin_user,	only: [:edit, :update, :destroy]

	def show
		@item = Item.find(params[:id])
		@current_user = current_user
		##debugger
	end

	def create 
		@item = Item.new(item_params) 
		if @item.save
			flash[:success] = "#{@item.name} has been successfully added!" 
			redirect_to @item 
		else 
			render 'new' 
		end 
	end


	def index
		@current_user = current_user

		# Index without React
		@items = Item.paginate(page: params[:page])
		
		# Index with React 
		#@items = Kaminari.paginate_array(Item.first(10)).page(params[:page])
	end


	def new
		@item = Item.new
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])
		if @item.update_attributes(item_params)
			flash[:success] = "Item updated"
			redirect_to @item
		else
			render 'edit'
		end
	end

	def destroy
		Item.find(params[:id]).destroy
		flash[:success] = "Item deleted"
		redirect_to items_url
	end

	private

		def item_params
			params.require(:item).permit(:name, :description, :price)
		end

		def search_items
			@item = if params[:search].present?
				Item.search(params[:search])
			else
				Item.all
			end.sorted.page(params[:page])
		end

end

app/views/items/_item.html.erb
<li>
	<%= link_to item.name, item %>
	<%= item.priceFormat %>
	
	<% if current_user.admin? && !current_user?(item) %>
    	| <%= link_to "delete", item, method: :delete, data: { confirm: "You sure?" } %>
	<% end %>

</li>

app/views/items/edit.html.erb
<% provide(:title, 'Edit Item') %>
<h1>Edit Item</h1>

<div class="row">
	<div class="col-md-6 
		col-md-offset-3">
		<%= form_for(@item) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>

		<%= f.label :name %>
		<%= f.text_field :name, 
			class: 'form-control' %>

		<%= f.label :description %>
		<%= f.text_area :description,
			class: 'form-control' %>

		<%= f.label :price %>
		<%= f.text_field :price,
			class: 'form-control' %>

		<%= f.submit "Save Changes", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/items/index.html.erb
<% provide(:title, 'All Items') %>

<h1>All items</h1>

<% if  @current_user && @current_user.admin? %>
	<h2>
		<%= link_to "Create New Item",new_item_path %>
	</h2>	
<% end %>

<%= will_paginate %>
	<ul class="items">
 		<%= render @items %>
	</ul>
<%= will_paginate %>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<% provide(:title, @item.name) %>
<h1>
	Name: <%= @item.name %> 
</h1>
<h2>

	Price: <%= @item.priceFormat %>
	<% if  @current_user && @current_user.admin? %>
		<ul><%= link_to "Edit item", edit_item_path(@item) %></ul>
<% end %>
</h2>



<p>
	Description: 
		<%= @item.description %> 
</p>